name: Upload Assets to S3(R2)

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整的 git history 以便生成正确的 tag
      -
        name: Get Version
        id: get_version
        run: |
          echo "VERSION=$(git describe --dirty --always --tags --abbrev=7)" >> $GITHUB_OUTPUT
      - 
        name: Deploy
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.S3_KEY_ID }}
          aws_secret_access_key: ${{ secrets.S3_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.S3_BUCKET }}
          source_dir: './'
          destination_dir: './'
          endpoint: ${{ secrets.S3_ENDPOINT }}
